### ISSUE TITLE
get flops failed

### ISSUE THREAD

**Issue by Rayn-Wu** [Yzichen/FlashOCC#4]
Thank you for your great work!

The provided code works well for the training task. However, when attempting to run the code for detecting FLOPs, I encountered the following issue. I would like to inquire whether the data for the model's parameter count in your paper was obtained using the code snippet below.

```
python tools/analysis_tools/get_flops.py projects/configs/flashocc/flashocc-r50.py  --shape 256 704
```
and the error is:
```
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 109, in <module>
    main()                                                       
  File "tools/analysis_tools/get_flops.py", line 83, in main     
    model = build_model(                                         
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\mmdet3d-1.0.0rc4-py3.8.egg\mmdet3d\models\builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\mmdet3d-1.0.0rc4-py3.8.egg\mmdet3d\models\builder.py", line 95, in build_detector
    return MMDET_DETECTORS.build(
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\mmcv\utils\registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'BEVDetOCC is not in the models registry'
```

However, the BEVDetOCC is already registered in file "projects/mmdet3d_plugin/models/detectors/bevdet_occ.py"
So, I was wondering how to fix that

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/blob/845a6a83abee73d830316763ea5f44be5f162499/tools/train.py#L127-L147

You need to add this code to the script to import the corresponding module. 
You can also refer to train.py and test.py to see how to add them.

**Comment by Rayn-Wu** [comment]
Thank you very much for your reply.
However, when I add the code above , the error goes like this:
```
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 130, in <module>
    main ()
  File "tools/analysis_tools/get_flops.py", line 119, in main
    flops, params = get_model_complexity_info (
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\mmcv\cnn\utils\flops_counter.py", line 94, in get_model_complexity_info
    _ = flops_model(**input)
  File "C:\Users\64679\anaconda3\envs\bevdet\lib\site-packages\torch\nn\modules\module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "E:\back\BaiduSyncdisk\graduation_prj\code\FlashOCC\projects\mmdet3d_plugin\models\detectors\bevdet.py", line 248, in forward_dummy
    assert self.with_pts_bbox
AssertionError
``` 
I think  the reason is that the "BEVDetOCC "class in file "mmdet3d_plugin/models/detectors/bevdet_occ.py" has no “forward_dummy” function to support such operation. 
I am wondering how to fix that and get the FLOPs of your flashocc model.
Looking forward to your reply :)

**Comment by Yzichen** [comment]
You're right, I've added the forward_dummy implementation to the latest commit.

**Comment by Rayn-Wu** [comment]
Thanks, the code now can run perfectly!
Thank you again for sharing this great project :)
