### ISSUE TITLE
测试FO_R50_M0报错

### ISSUE THREAD

**Issue by XupengFu** [Yzichen/FlashOCC#50]
作者你好，我在测试FO_R50_M0时程序报错。下面我直接把结果贴出来
python /home/fxp/Projects/FlashOCC/tools/test.py /home/fxp/Projects/FlashOCC/projects/configs/flashocc/flashocc-r50-M0.py /home/fxp/Projects/FlashOCC/ckpts/flashocc-r50-M0-256x704.pth --eval mAP 

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/fxp/anaconda3/envs/flashocc/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/fxp/anaconda3/envs/flashocc/lib/python3.8/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/fxp/anaconda3/envs/flashocc/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 513: invalid start byte

Original exception was:
Traceback (most recent call last):
  File "/home/fxp/Projects/FlashOCC/tools/test.py", line 290, in <module>
    main()
  File "/home/fxp/Projects/FlashOCC/tools/test.py", line 260, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/fxp/Projects/FlashOCC/mmdetection3d/mmdet3d/apis/test.py", line 40, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/fxp/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fxp/anaconda3/envs/flashocc/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/fxp/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/fxp/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fxp/anaconda3/envs/flashocc/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/home/fxp/Projects/FlashOCC/mmdetection3d/mmdet3d/models/detectors/base.py", line 62, in forward
    return self.forward_test(**kwargs)
  File "/home/fxp/Projects/FlashOCC/projects/mmdet3d_plugin/models/detectors/bevdet.py", line 237, in forward_test
    return self.simple_test(points[0], img_metas[0], img_inputs[0],
  File "/home/fxp/Projects/FlashOCC/projects/mmdet3d_plugin/models/detectors/bevdet_occ.py", line 165, in simple_test
  File "/home/fxp/Projects/FlashOCC/projects/mmdet3d_plugin/models/detectors/bevdet_occ.py", line 179, in simple_test_occ
  File "/home/fxp/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BEVOCCHead2D' object has no attribute 'get_occ_gpu'

下面是代码图片
![2024-07-10_21-20](https://github.com/Yzichen/FlashOCC/assets/147971139/b65d808c-cf48-47ad-a743-c80260e83760)

实际上get_occ_gpu在class BEVOCCHead2D_V2(BaseModule)下定义，如图所示
![2024-07-10_21-21](https://github.com/Yzichen/FlashOCC/assets/147971139/e5d3c9ca-1f52-46bf-98b5-765aa844453a)

**Comment by Wj-costumer** [comment]
![image](https://github.com/user-attachments/assets/d85d344d-fc4e-457f-88be-87319f108359)
配置文件这里修改成BEVOCCHead2D_V2就能run了

**Comment by Rogersljs** [comment]
谢谢您！经过以上修改后，出现了Starting Evaluation...
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 286, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/leapting/work/2024-07-17-FlashOcc/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 106, in evaluate
    occ_pred = occ_results[data_id]['pred_occ'].cpu().numpy()  # (Dx, Dy, Dz)
IndexError: too many indices for tensor of dimension 3
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 41693) of binary: /home/leapting/anaconda3/envs/flashocc/bin/python
Traceback (most recent call last):
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/leapting/anaconda3/envs/flashocc/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-19_16:12:02
  host      : leapting-Precision-3571
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 41693)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
的问题。
  File "/home/leapting/work/2024-07-17-FlashOcc/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 106, in evaluate
    occ_pred = occ_results[data_id]['pred_occ'].cpu().numpy()  # (Dx, Dy, Dz)
IndexError: too many indices for tensor of dimension 3
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 41693) of binary: /home/leapting/anaconda3/envs/flashocc/bin/python
要怎么修改呢？

**Comment by drilistbox** [comment]
问题解决了。更新下代码，重新下载权重文件。

**Comment by xzyun2011** [comment]
老哥解决这个问题了吗？代码更新的是 panoptic-flashocc-r50-depth.py， Get Started里面用的是 projects/configs/flashocc/flashocc-r50.py

**Comment by Rogersljs** [comment]
就是配置文件 都一样 没关系 我改了nuscenes-dataset-occ.py的eval函数 在issue里写了发自我的 iPhone在 2024年8月12日，11:31，xzyun2011 ***@***.***> 写道：﻿
老哥解决这个问题了吗？代码更新的是 panoptic-flashocc-r50-depth.py， Get Started里面用的是 projects/configs/flashocc/flashocc-r50.py

**Comment by drilistbox** [comment]
啥意思 还跑步起来么，之前更新了代码后可以跑了，有更新代码么？

**Comment by xzyun2011** [comment]
> 啥意思 还跑步起来么，之前更新了代码后可以跑了，有更新代码么？

更新过了，需要修改配置文件比如flashocc-r50.py里 "type='BEVOCCHead2D" 改为 "type='BEVOCCHead2D_V2'" 就行

**Comment by shaozheng777** [comment]
ello, I encountered the following issue while running test.py. Have you experienced this problem before? How should I resolve it?Starting Evaluation...
  0%|                                                                                                                                                                          | 0/162 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 286, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 140, in evaluate
    self.occ_eval_metrics.add_batch(
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 172, in add_batch
    _, _hist = self.compute_mIoU(masked_semantics_pred, masked_semantics_gt, self.num_classes)
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 141, in compute_mIoU
    new_hist, correct, labeled = self.hist_info(n_classes, pred.flatten(), label.flatten())
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 118, in hist_info
    n_cl * gt[k].astype(int) + pred[k].astype(int), minlength=n_cl ** 2   
AttributeError: 'Tensor' object has no attribute 'astype'
