### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'astype'

### ISSUE THREAD

**Issue by shaozheng777** [Yzichen/FlashOCC#66]
Hello, thank you for your great work! But I encountered the following issue while running test.py.  How should I resolve it?
Starting Evaluation...
  0%|                                                                                                                                                                          | 0/162 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 286, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 140, in evaluate
    self.occ_eval_metrics.add_batch(
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 172, in add_batch
    _, _hist = self.compute_mIoU(masked_semantics_pred, masked_semantics_gt, self.num_classes)
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 141, in compute_mIoU
    new_hist, correct, labeled = self.hist_info(n_classes, pred.flatten(), label.flatten())
  File "/home/wh/code/FlashOCC/projects/mmdet3d_plugin/core/evaluation/occ_metrics.py", line 118, in hist_info
    n_cl * gt[k].astype(int) + pred[k].astype(int), minlength=n_cl ** 2   
AttributeError: 'Tensor' object has no attribute 'astype'

**Comment by drilistbox** [comment]
Is torch version right?

**Comment by UriLin** [comment]
Hi, I encountered the same error. Did you solve it?

**Comment by shaozheng777** [comment]
> Is torch version right?

Thank you for your concern, but I'm sure my version of torch is correct.

**Comment by drilistbox** [comment]
What is your test cmd

**Comment by shaozheng777** [comment]
> Hi, I encountered the same error. Did you solve it?

我重新下载了一下代码就好了

**Comment by shaozheng777** [comment]
> What is your test cmd

python tools/test.py /home/wh/code/FlashOCC/projects/configs/flashocc/flashocc-stbase-4d-stereo-512x1408_4x4_1e-2.py /home/wh/code/FlashOCC/ckpts/flashocc-stbase-4d-stereo-512x1408.pth --eval mAP
