### ISSUE TITLE
运行tensorrt eval报错

### ISSUE THREAD

**Issue by upupbo** [Yzichen/FlashOCC#90]
代码：python -u tools/analysis_tools/benchmark_trt.py $config $engine --eval >benchmark_trt_int8_eval.log 2>&1 &
报错：Done image [6000/ 500], fps: 160.89 img / s
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark_trt.py", line 282, in <module>
    fps = main()
  File "tools/analysis_tools/benchmark_trt.py", line 278, in main
    print(dataset.evaluate(results, **eval_kwargs))
  File "/data/public/engineers/chenbo/occ_project/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 71, in evaluate
    metric = eval_kwargs['metric'][0]
TypeError: 'bool' object is not subscriptable

**Comment by Yzichen** [comment]
https://github.com/Yzichen/FlashOCC/blob/4084861d8d605bb01df55fcbc8072036055aa625/tools/analysis_tools/benchmark_trt.py#L277

You can modify it to:
`eval_kwargs.update(dict(metric='ray-iou')) `
or `eval_kwargs.update(dict(metric='miou'))`
